language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feedtwo ./udagram-api-feed
  - docker build -t udagram-api-usertwo ./udagram-api-user
  - docker build -t udagram-frontendtwo ./udagram-frontend
  - docker build -t reverseproxytwo ./udagram-reverseproxy
  - docker tag udagram-api-feedtwo dlb34/udagram-api-feedtwo
  - docker tag udagram-api-usertwo dlb34/udagram-api-usertwo
  - docker tag udagram-frontendtwo dlb34/udagram-frontendtwo
  - docker tag reverseproxytwo dlb34/reverseproxytwo

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push dlb34/udagram-api-feedtwo
  - docker push dlb34/udagram-api-usertwo
  - docker push dlb34/udagram-frontendtwo
  - docker push dlb34/reverseproxytwo